---
title: "4180 Chattanooga Crime Data"
author: "Thomas Raines, Yatri Patel"
date: "10/15/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(reshape2)
library(lubridate)
library(sf)
library(raster)
library(ggplot2)
library(incidence)
library(plotly)
library(leaflet)
```



```{r}
#read the main police incident database
police_incident <- read_csv("Police_Incident_Data.csv")

head(police_incident)
```


```{r}
censusPopData <- read_csv('Census_2020_Tract_Populations.csv')

head(censusPopData)

colnames(censusPopData)[3] <- "TRACT_ID"
```

```{r}
censusIncData <- read_csv('2020_Median_Income.csv')
head(censusIncData)
```

```{r}
#merge the income and population data

censusData <- merge(censusPopData,censusIncData,by="TRACT_ID")

head(censusData)


```


```{r}
## Make shape file for Census Population
censusPopShp <- read_sf("Census 2020 Tract Populations/geo_export_6ea9b8b9-f93b-41bd-8242-39b59cd81ddc.shp")
head(censusPopShp)
```


```{r}
## Make shape file for 2017 Median Income
censusIncShp <- read_sf("2020 Median Income/geo_export_43a087a5-8ff8-4733-9a99-dd658a9c17f4.shp")

censusIncShp <- censusIncShp %>%
  rename(tract = tract_id)

head(censusIncShp)
```


```{r}
## Merge our Shape Files to one big shape file
sf::sf_use_s2(FALSE)
censusDataShp <- st_join(censusIncShp, censusPopShp)
head(censusDataShp)
plot(censusDataShp, max.plot = 31)

censusDataShp[is.na(censusDataShp)] <- 0
```


```{r}
## Plot in ggplot

income_plot <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$median_inc)) +
  theme_classic() +
  theme_dark() + 
  labs(title = "Median Income for Chattanooga Tracts", fill = "Median Income")

ggplotly(income_plot)
```


## START OF MILESTONE 2 -----------------------------------------------------------------------------------------------------------------------------------------------------

```{r}

## Make Plot for population:
population_plot <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$total_popu)) +
  theme_classic() +
  theme_dark() + 
  labs(title = "Population for Chattanooga Tracts", fill = "Total Population")

ggplotly(population_plot)

```

```{r}
##Remove the Time Stamps from the Date Incidents
police_incident$Date_Incident <- str_sub(police_incident$Date_Incident, 1, nchar(police_incident$Date_Incident)-12)

head(police_incident)
```

```{r}
##Make Incident Dates date type
police_incident$Date_Incident <- as.Date(police_incident$Date_Incident, format = "%m/%d/%Y")

head(police_incident)
```

```{r}
#plot number of incident by date 
police_incident_by_date <- police_incident %>% group_by(Date_Incident) %>% summarise(frequency = n())

p <- ggplot(police_incident_by_date, aes(x = police_incident_by_date$Date_Incident, y = police_incident_by_date$frequency)) + geom_col(fill="#BE93D4") + geom_smooth() + xlab("Year") + ylab("Number of Incident") + labs(title = "Police incident by Date")

ggplotly(p)
```

```{r}
#plot number of incident by month 
police_incident_by_month <- police_incident_by_date %>% group_by(Date_Incident=floor_date(Date_Incident, "month")) %>%
   summarize(frequency=sum(frequency))

p <- ggplot(police_incident_by_month, aes(x = police_incident_by_month$Date_Incident, y = police_incident_by_month$frequency)) + geom_col(fill="#BE93D4") + geom_smooth() + xlab("Month") + ylab("Number of Incident") + labs(title = "Police Incident by Month")

ggplotly(p)

```

```{r}
#plot number of incident by year
police_incident_by_year <- police_incident_by_month %>% group_by(Date_Incident=floor_date(Date_Incident, "year")) %>%
   summarize(frequency=sum(frequency))

p <- ggplot(police_incident_by_year, aes(x = police_incident_by_year$Date_Incident, y = police_incident_by_year$frequency)) + geom_col(fill="#BE93D4") + geom_smooth() + xlab("Year") + ylab("Number of Incident") + labs(title = "Police Incident by Year")

ggplotly(p)
```

```{r}
#police incident number by incident type
police_incident_by_type <- police_incident %>% group_by(Incident_Type) %>% summarise(frequency = n())

police_incident_by_type$Incident_Type <- factor(police_incident_by_type$Incident_Type, levels = unique(police_incident_by_type$Incident_Type)[order(police_incident_by_type$frequency, decreasing = TRUE)])

p <- ggplot(police_incident_by_type, aes(x = police_incident_by_type$Incident_Type, y = police_incident_by_type$frequency)) + geom_col(fill="#BE93D4") + geom_smooth() + xlab("Type") + ylab("Number of Incident") + labs(title = "Police Incident by Incident Type")

ggplotly(p)
```

```{r}
#police incident number by incident description
police_incident_by_description <- police_incident %>% group_by(Incident_Description) %>% summarise(frequency = n())

police_incident_by_description$Incident_Description <- factor(police_incident_by_description$Incident_Description, levels = unique(police_incident_by_description$Incident_Description)[order(police_incident_by_description$frequency, decreasing = TRUE)])

p <- ggplot(police_incident_by_description, aes(x = police_incident_by_description$Incident_Description, y = police_incident_by_description$frequency)) + geom_col(fill="#BE93D4") + xlab("Description") + ylab("Number of Incident") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +  labs(title = "Police Incident by Incident Description")

ggplotly(p)

```

## START OF MILESTONE 3 -----------------------------------------------------------------------------------------------------------------------------------------------------

```{r}
#plot number of incident by specific month for 2020
police_incident_by_month <- police_incident_by_date %>% group_by(Date_Incident=floor_date(Date_Incident, "month")) %>% summarize(frequency=sum(frequency)) 

police_incident_by_month_spec <- police_incident_by_month[police_incident_by_month$Date_Incident >= "2020-01-01" & police_incident_by_month$Date_Incident <= "2020-12-31",]


p <- ggplot(police_incident_by_month_spec, aes(x = police_incident_by_month_spec$Date_Incident, y = police_incident_by_month_spec$frequency)) + geom_col(fill="#BE93D4") + geom_smooth() + xlab("Month") + ylab("Number of Incident") + labs(title = "Police Incident for 2020 aggregated by Month")

ggplotly(p)
```

```{r}
##Make 2020 Police incident df
police_incident_2020 <- police_incident[police_incident$Date_Incident >= "2020-01-01" & police_incident$Date_Incident <= "2020-12-31",]

head(police_incident_2020)

```

```{r}
##Refine Data Frame to Just show may (Highest Crime cases)
pi_may_2020 <-  police_incident[police_incident$Date_Incident >= "2020-05-01" & police_incident$Date_Incident <= "2020-05-31",]

head(pi_may_2020)

```

```{r}
## Make leaflet plot for police incidents in the month of 2020 with the highest crime (May 20')
inc_map_may_2020 <- ggplot() +
  geom_sf(data = censusDataShp, aes()) +
  geom_point(data = pi_may_2020, aes(x=pi_may_2020$Longitude, y=pi_may_2020$Latitude, color=pi_may_2020$Incident_Type))  + labs(title="Location of Police Inicidents in May of 2020", x="Longitude", y= "Latitude", color="Incident Type") +theme(legend.position="bottom")

ggplotly(inc_map_may_2020)
```

```{r}
##Refine DataFrame to show only part one crimes in may 2020
pi_type1_crimes_2020 <- pi_may_2020 %>% filter(pi_may_2020$Incident_Type == "Part 1 Crimes")

```

```{r}
## Make leaflet plot for part one police incidents in the month of may in 2020
p1_may_map <- ggplot() +
  geom_sf(data = censusDataShp, aes()) +
  geom_point(data = pi_type1_crimes_2020, aes(x=pi_type1_crimes_2020$Longitude, y=pi_type1_crimes_2020$Latitude, color=pi_type1_crimes_2020$Incident_Description)) + labs(title="Location of Part 1 Police Inicidents in May of 2020", x="Longitude", y= "Latitude", color="Incident Description") +theme(legend.position="bottom")


ggplotly(p1_may_map)

```

```{r}
##Refine DataFrame to show only robbery crimes in may 2020
p1_Crimes_may_2020_robbery <- pi_may_2020 %>% filter(pi_may_2020$Incident_Description == "Robbery")

head(p1_Crimes_may_2020_robbery)

```

```{r}
## Make leaflet plot for part one police incidents (robberies) in the month of may in 2020
p1_may_map_robbery <- ggplot() +
  geom_sf(data = censusDataShp, aes()) +
  geom_point(data = p1_Crimes_may_2020_robbery, aes(x=p1_Crimes_may_2020_robbery$Longitude, y=p1_Crimes_may_2020_robbery$Latitude, color=p1_Crimes_may_2020_robbery$Incident_Description)) + labs(title="Location of Robberies in May of 2020", x="Longitude", y= "Latitude", color="Incident Type")


ggplotly(p1_may_map_robbery)

```



##Start of Milestone 4 -----------------------------------------------------------------------------------------------------------------------------
```{r}
##Make a plot overlaying the shapefile population data with the amounts of Part one crimes
p <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$total_popu)) +
  geom_point(data = p1_Crimes_may_2020_robbery, aes(x=p1_Crimes_may_2020_robbery$Longitude, y=p1_Crimes_may_2020_robbery$Latitude, color=p1_Crimes_may_2020_robbery$Incident_Description)) + labs(title="Location of Robberies in May of 2020", x="Longitude", y= "Latitude", color="Incident Type", fill= "Population")

ggplotly(p)
```

```{r}
##Make a plot overlaying the shapefile income data with the amounts of Part one crimes
p <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$median_inc)) +
  geom_point(data = p1_Crimes_may_2020_robbery, aes(x=p1_Crimes_may_2020_robbery$Longitude, y=p1_Crimes_may_2020_robbery$Latitude, color=p1_Crimes_may_2020_robbery$Incident_Description)) + labs(title="Location of Robberies in May of 2020", x="Longitude", y= "Latitude", color="Incident Type", fill= "Median Income")

ggplotly(p)
```


```{r}
##Make new dataframe for p1_Crimes_may_2020_shoplifting
#Shoplifting

p1_Crimes_may_2020_shoplifting <- pi_may_2020 %>% filter(pi_may_2020$Incident_Description == "Shoplifting")

head(p1_Crimes_may_2020_shoplifting)

#combined dataframe for robbery and shoplifting
p1_shoplift_robbery <-  rbind(p1_Crimes_may_2020_robbery,p1_Crimes_may_2020_shoplifting)
```


```{r}
p <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$median_inc)) +
  geom_point(data = p1_shoplift_robbery, aes(x=p1_shoplift_robbery$Longitude, y=p1_shoplift_robbery$Latitude, color= p1_shoplift_robbery$Incident_Description))+
 labs(title="Location of Robberies and Shoplifting incidents in May of 2020", x="Longitude", y= "Latitude", color="Incident Description", fill= "Median Income")


ggplotly(p)
```


```{r}
p <- ggplot() +
  geom_sf(data = censusDataShp, aes(fill=censusDataShp$total_popu)) +
  geom_point(data = p1_shoplift_robbery, aes(x=p1_shoplift_robbery$Longitude, y=p1_shoplift_robbery$Latitude, color= p1_shoplift_robbery$Incident_Description))+
 labs(title="Location of Robberies and Shoplifting incidents in May of 2020", x="Longitude", y= "Latitude", color="Incident Description", fill= "Population")


ggplotly(p)
```

